// Common LOINC codes for laboratory tests
// Source: https://loinc.org

import { LOINCCode } from "@/types/laboratory";

export const COMMON_LOINC_CODES: Record<string, LOINCCode> = {
  // Complete Blood Count (CBC)
  CBC_WBC: {
    code: "6690-2",
    display: "Leukocytes [#/volume] in Blood by Automated count",
    system: "http://loinc.org",
    component: "Leukocytes",
    property: "NCnc",
    timing: "Pt",
    systemType: "Bld",
    scale: "Qn",
  },
  CBC_RBC: {
    code: "789-8",
    display: "Erythrocytes [#/volume] in Blood by Automated count",
    system: "http://loinc.org",
    component: "Erythrocytes",
    property: "NCnc",
    timing: "Pt",
    systemType: "Bld",
    scale: "Qn",
  },
  CBC_HGB: {
    code: "718-7",
    display: "Hemoglobin [Mass/volume] in Blood",
    system: "http://loinc.org",
    component: "Hemoglobin",
    property: "MCnc",
    timing: "Pt",
    systemType: "Bld",
    scale: "Qn",
  },
  CBC_HCT: {
    code: "4544-3",
    display: "Hematocrit [Volume Fraction] of Blood by Automated count",
    system: "http://loinc.org",
    component: "Hematocrit",
    property: "VFr",
    timing: "Pt",
    systemType: "Bld",
    scale: "Qn",
  },
  CBC_PLT: {
    code: "777-3",
    display: "Platelets [#/volume] in Blood by Automated count",
    system: "http://loinc.org",
    component: "Platelets",
    property: "NCnc",
    timing: "Pt",
    systemType: "Bld",
    scale: "Qn",
  },

  // Basic Metabolic Panel (BMP)
  BMP_GLUCOSE: {
    code: "2345-7",
    display: "Glucose [Mass/volume] in Serum or Plasma",
    system: "http://loinc.org",
    component: "Glucose",
    property: "MCnc",
    timing: "Pt",
    systemType: "Ser/Plas",
    scale: "Qn",
  },
  BMP_BUN: {
    code: "3094-0",
    display: "Urea nitrogen [Mass/volume] in Serum or Plasma",
    system: "http://loinc.org",
    component: "Urea nitrogen",
    property: "MCnc",
    timing: "Pt",
    systemType: "Ser/Plas",
    scale: "Qn",
  },
  BMP_CREATININE: {
    code: "2160-0",
    display: "Creatinine [Mass/volume] in Serum or Plasma",
    system: "http://loinc.org",
    component: "Creatinine",
    property: "MCnc",
    timing: "Pt",
    systemType: "Ser/Plas",
    scale: "Qn",
  },
  BMP_SODIUM: {
    code: "2951-2",
    display: "Sodium [Moles/volume] in Serum or Plasma",
    system: "http://loinc.org",
    component: "Sodium",
    property: "SCnc",
    timing: "Pt",
    systemType: "Ser/Plas",
    scale: "Qn",
  },
  BMP_POTASSIUM: {
    code: "2823-3",
    display: "Potassium [Moles/volume] in Serum or Plasma",
    system: "http://loinc.org",
    component: "Potassium",
    property: "SCnc",
    timing: "Pt",
    systemType: "Ser/Plas",
    scale: "Qn",
  },
  BMP_CHLORIDE: {
    code: "2075-0",
    display: "Chloride [Moles/volume] in Serum or Plasma",
    system: "http://loinc.org",
    component: "Chloride",
    property: "SCnc",
    timing: "Pt",
    systemType: "Ser/Plas",
    scale: "Qn",
  },
  BMP_CO2: {
    code: "2028-9",
    display: "Carbon dioxide, total [Moles/volume] in Serum or Plasma",
    system: "http://loinc.org",
    component: "Carbon dioxide",
    property: "SCnc",
    timing: "Pt",
    systemType: "Ser/Plas",
    scale: "Qn",
  },

  // Liver Function Tests
  LFT_ALT: {
    code: "1742-6",
    display:
      "Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma",
    system: "http://loinc.org",
    component: "Alanine aminotransferase",
    property: "CCnc",
    timing: "Pt",
    systemType: "Ser/Plas",
    scale: "Qn",
  },
  LFT_AST: {
    code: "1920-8",
    display:
      "Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma",
    system: "http://loinc.org",
    component: "Aspartate aminotransferase",
    property: "CCnc",
    timing: "Pt",
    systemType: "Ser/Plas",
    scale: "Qn",
  },
  LFT_BILIRUBIN_TOTAL: {
    code: "1975-2",
    display: "Bilirubin.total [Mass/volume] in Serum or Plasma",
    system: "http://loinc.org",
    component: "Bilirubin.total",
    property: "MCnc",
    timing: "Pt",
    systemType: "Ser/Plas",
    scale: "Qn",
  },
  LFT_ALBUMIN: {
    code: "1751-7",
    display: "Albumin [Mass/volume] in Serum or Plasma",
    system: "http://loinc.org",
    component: "Albumin",
    property: "MCnc",
    timing: "Pt",
    systemType: "Ser/Plas",
    scale: "Qn",
  },
  LFT_ALP: {
    code: "6768-6",
    display:
      "Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma",
    system: "http://loinc.org",
    component: "Alkaline phosphatase",
    property: "CCnc",
    timing: "Pt",
    systemType: "Ser/Plas",
    scale: "Qn",
  },

  // Lipid Panel
  LIPID_CHOLESTEROL: {
    code: "2093-3",
    display: "Cholesterol [Mass/volume] in Serum or Plasma",
    system: "http://loinc.org",
    component: "Cholesterol",
    property: "MCnc",
    timing: "Pt",
    systemType: "Ser/Plas",
    scale: "Qn",
  },
  LIPID_HDL: {
    code: "2085-9",
    display: "Cholesterol in HDL [Mass/volume] in Serum or Plasma",
    system: "http://loinc.org",
    component: "Cholesterol in HDL",
    property: "MCnc",
    timing: "Pt",
    systemType: "Ser/Plas",
    scale: "Qn",
  },
  LIPID_LDL: {
    code: "2089-1",
    display: "Cholesterol in LDL [Mass/volume] in Serum or Plasma",
    system: "http://loinc.org",
    component: "Cholesterol in LDL",
    property: "MCnc",
    timing: "Pt",
    systemType: "Ser/Plas",
    scale: "Qn",
  },
  LIPID_TRIGLYCERIDES: {
    code: "2571-8",
    display: "Triglyceride [Mass/volume] in Serum or Plasma",
    system: "http://loinc.org",
    component: "Triglyceride",
    property: "MCnc",
    timing: "Pt",
    systemType: "Ser/Plas",
    scale: "Qn",
  },

  // Thyroid Function
  THYROID_TSH: {
    code: "3016-3",
    display: "Thyrotropin [Units/volume] in Serum or Plasma",
    system: "http://loinc.org",
    component: "Thyrotropin",
    property: "ACnc",
    timing: "Pt",
    systemType: "Ser/Plas",
    scale: "Qn",
  },
  THYROID_T4: {
    code: "3026-2",
    display: "Thyroxine (T4) [Mass/volume] in Serum or Plasma",
    system: "http://loinc.org",
    component: "Thyroxine",
    property: "MCnc",
    timing: "Pt",
    systemType: "Ser/Plas",
    scale: "Qn",
  },
  THYROID_T3: {
    code: "3053-6",
    display: "Triiodothyronine (T3) [Mass/volume] in Serum or Plasma",
    system: "http://loinc.org",
    component: "Triiodothyronine",
    property: "MCnc",
    timing: "Pt",
    systemType: "Ser/Plas",
    scale: "Qn",
  },

  // Cardiac Markers
  CARDIAC_TROPONIN: {
    code: "6598-7",
    display: "Troponin I.cardiac [Mass/volume] in Serum or Plasma",
    system: "http://loinc.org",
    component: "Troponin I.cardiac",
    property: "MCnc",
    timing: "Pt",
    systemType: "Ser/Plas",
    scale: "Qn",
  },
  CARDIAC_BNP: {
    code: "30934-4",
    display:
      "Natriuretic peptide.B prohormone.N-Terminal [Mass/volume] in Serum or Plasma",
    system: "http://loinc.org",
    component: "Natriuretic peptide.B prohormone.N-Terminal",
    property: "MCnc",
    timing: "Pt",
    systemType: "Ser/Plas",
    scale: "Qn",
  },

  // Coagulation
  COAG_PT: {
    code: "5902-2",
    display: "Prothrombin time (PT)",
    system: "http://loinc.org",
    component: "Prothrombin time",
    property: "Time",
    timing: "Pt",
    systemType: "PPP",
    scale: "Qn",
  },
  COAG_INR: {
    code: "6301-6",
    display: "INR in Platelet poor plasma by Coagulation assay",
    system: "http://loinc.org",
    component: "INR",
    property: "RelRto",
    timing: "Pt",
    systemType: "PPP",
    scale: "Qn",
  },
  COAG_APTT: {
    code: "3173-2",
    display: "aPTT in Blood by Coagulation assay",
    system: "http://loinc.org",
    component: "aPTT",
    property: "Time",
    timing: "Pt",
    systemType: "Bld",
    scale: "Qn",
  },

  // Urinalysis
  URINE_PROTEIN: {
    code: "2888-6",
    display: "Protein [Mass/volume] in Urine",
    system: "http://loinc.org",
    component: "Protein",
    property: "MCnc",
    timing: "Pt",
    systemType: "Urine",
    scale: "Qn",
  },
  URINE_GLUCOSE: {
    code: "2349-9",
    display: "Glucose [Mass/volume] in Urine",
    system: "http://loinc.org",
    component: "Glucose",
    property: "MCnc",
    timing: "Pt",
    systemType: "Urine",
    scale: "Qn",
  },

  // Hemoglobin A1C
  HBA1C: {
    code: "4548-4",
    display: "Hemoglobin A1c/Hemoglobin.total in Blood",
    system: "http://loinc.org",
    component: "Hemoglobin A1c/Hemoglobin.total",
    property: "MFr",
    timing: "Pt",
    systemType: "Bld",
    scale: "Qn",
  },

  // Vitamin D
  VITAMIN_D: {
    code: "1989-3",
    display:
      "25-Hydroxyvitamin D3+25-Hydroxyvitamin D2 [Mass/volume] in Serum or Plasma",
    system: "http://loinc.org",
    component: "25-Hydroxyvitamin D",
    property: "MCnc",
    timing: "Pt",
    systemType: "Ser/Plas",
    scale: "Qn",
  },
};
